name: svgaplayer_plus
description: The SVGAPlayer implementation of Flutter using CustomPainter, with support for audio playback.
version: 2.3.1
homepage: https://github.com/InjoyDeng/SVGAPlayer-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  http: ^1.2.2
  path_drawing: ^1.0.0
  archive: ^3.1.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
