name: svgaplayer_plus
description: The SVGAPlayer implementation of Flutter using CustomPainter, with support for audio playback.
version: 2.3.1
homepage: https://github.com/InjoyDeng/SVGAPlayer-Flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  http: ^1.2.2
  path_drawing:
    git:
      url: https://github.com/wanwenfeng4798/flutter_path_drawing/
      ref: master
  archive: ^4.0.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0